/* Generated by Together */

package es.altia.common.service.mail.exception;

import es.altia.common.exception.FunctionalException;


public class MailException extends FunctionalException {
        /**
     * Create a <code>DemandaException</code> and set the exception error
     * message.
     *
     * @param theMessage the message
     */
    public MailException(String theMessage) {
        this(theMessage, null);
    }

    /**
     * Create a <code>DemandaException</code> and set the exception object
     * that caused this exception.
     *
     * @param theMessage   the detail of the error message
     * @param theException the original exception
     */
    public MailException(String theMessage, Throwable theException)
    {
        super(theMessage, theException);
    }

}
